# path-sync copy -n python-template
name: setup
description: 'Setup Python, uv, and just for CI'

inputs:
  python-version:
    default: '3.13'
    description: 'Python version to use'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "${{ inputs.python-version }}"
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
    - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
    - name: git-configure
      shell: bash
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email github-actions[bot]@users.noreply.github.com
