# === DO_NOT_EDIT: pkg-ext header ===
"""Example classes for sections group. Generated by pkg-ext."""

from collections.abc import Callable
from pathlib import Path
from typing import Generic, Self, TypeVar

from pydantic import BaseModel, Field

from zero_3rdparty._internal.sections import CommentConfig, Section

T = TypeVar("T")


class Example(BaseModel, Generic[T]):
    example_name: str
    example_description_md: str = ""
    expected: Callable[[Self, T], None] = Field(exclude=True)


# === OK_EDIT: pkg-ext header ===

# Common fixtures
HASH_CONFIG = CommentConfig("#")
HTML_CONFIG = CommentConfig("<!--", " -->")

JUSTFILE_CONTENT = """\
# header line

# === OK_EDIT: mytool header ===
# Custom variables

# === DO_NOT_EDIT: mytool standard ===
pre-push: lint test
# === OK_EDIT: mytool standard ===

# === DO_NOT_EDIT: mytool coverage ===
cov:
  uv run pytest --cov
# === OK_EDIT: mytool coverage ===
"""


# === DO_NOT_EDIT: pkg-ext class_commentconfig ===
class CommentConfigExample(Example[CommentConfig]):
    prefix: str = ...  # type: ignore
    suffix: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_commentconfig ===


def _assert_comment_config(ex: CommentConfigExample, result: CommentConfig) -> None:
    assert result.prefix == ex.prefix
    assert result.suffix == ex.suffix


comment_config_hash = CommentConfigExample(
    example_name="hash_comments",
    prefix="#",
    suffix="",
    expected=_assert_comment_config,
)

comment_config_html = CommentConfigExample(
    example_name="html_comments",
    prefix="<!--",
    suffix=" -->",
    expected=_assert_comment_config,
)


# === DO_NOT_EDIT: pkg-ext class_get_comment_config ===
class GetCommentConfigExample(Example[CommentConfig]):
    path: Path | str = ...  # type: ignore
    override: CommentConfig | None = ...  # type: ignore


# === OK_EDIT: pkg-ext class_get_comment_config ===


def _assert_python_config(ex: GetCommentConfigExample, result: CommentConfig) -> None:
    assert result.prefix == "#"
    assert result.suffix == ""


def _assert_markdown_config(ex: GetCommentConfigExample, result: CommentConfig) -> None:
    assert result.prefix == "<!--"
    assert result.suffix == " -->"


def _assert_override_config(ex: GetCommentConfigExample, result: CommentConfig) -> None:
    assert result.prefix == "%%"
    assert result.suffix == ""


get_comment_config_python = GetCommentConfigExample(
    example_name="python_file",
    path=Path("test.py"),
    override=None,
    expected=_assert_python_config,
)

get_comment_config_markdown = GetCommentConfigExample(
    example_name="markdown_file",
    path=Path("test.md"),
    override=None,
    expected=_assert_markdown_config,
)

get_comment_config_override = GetCommentConfigExample(
    example_name="with_override",
    path=Path("test.py"),
    override=CommentConfig("%%"),
    expected=_assert_override_config,
)


# === DO_NOT_EDIT: pkg-ext class_parse_sections ===
class ParseSectionsExample(Example[list[Section]]):
    content: str = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore


# === OK_EDIT: pkg-ext class_parse_sections ===


def _assert_justfile_sections(ex: ParseSectionsExample, result: list[Section]) -> None:
    assert len(result) == 2
    assert result[0].id == "standard"
    assert result[0].content == "pre-push: lint test"


def _assert_html_sections(ex: ParseSectionsExample, result: list[Section]) -> None:
    assert len(result) == 1
    assert result[0].id == "heading"
    assert result[0].content == "# Title"


parse_sections_justfile = ParseSectionsExample(
    example_name="justfile_sections",
    content=JUSTFILE_CONTENT,
    tool_name="mytool",
    config=HASH_CONFIG,
    expected=_assert_justfile_sections,
)

parse_sections_html = ParseSectionsExample(
    example_name="html_sections",
    content="""\
<!-- === DO_NOT_EDIT: pkg heading === -->
# Title
<!-- === OK_EDIT: pkg heading === -->
""",
    tool_name="pkg",
    config=HTML_CONFIG,
    expected=_assert_html_sections,
)


# === DO_NOT_EDIT: pkg-ext class_replace_sections ===
class ReplaceSectionsExample(Example[str]):
    dest_content: str = ...  # type: ignore
    src_sections: dict[str, str] = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore
    skip_sections: list[str] | None = ...  # type: ignore


# === OK_EDIT: pkg-ext class_replace_sections ===


def _assert_replace_existing(ex: ReplaceSectionsExample, result: str) -> None:
    assert "new content" in result
    assert "old content" not in result


def _assert_skip_section(ex: ReplaceSectionsExample, result: str) -> None:
    assert "preserved" in result
    assert "would be replaced" not in result


replace_sections_existing = ReplaceSectionsExample(
    example_name="replace_existing",
    dest_content="""\
# === DO_NOT_EDIT: t std ===
old content
# === OK_EDIT: t std ===""",
    src_sections={"std": "new content"},
    tool_name="t",
    config=HASH_CONFIG,
    skip_sections=None,
    expected=_assert_replace_existing,
)

replace_sections_skip = ReplaceSectionsExample(
    example_name="skip_section",
    dest_content="""\
# === DO_NOT_EDIT: t std ===
preserved
# === OK_EDIT: t std ===""",
    src_sections={"std": "would be replaced"},
    tool_name="t",
    config=HASH_CONFIG,
    skip_sections=["std"],
    expected=_assert_skip_section,
)
