# === DO_NOT_EDIT: pkg-ext header ===
"""Example classes for sections group. Generated by pkg-ext."""

from pathlib import Path

from pydantic import BaseModel

from zero_3rdparty._internal.sections import CommentConfig


class Example(BaseModel):
    example_name: str
    example_description_md: str = ""


# === OK_EDIT: pkg-ext header ===

# Common fixtures
HASH_CONFIG = CommentConfig("#")
HTML_CONFIG = CommentConfig("<!--", " -->")

JUSTFILE_CONTENT = """\
# header line

# === OK_EDIT: mytool header ===
# Custom variables

# === DO_NOT_EDIT: mytool standard ===
pre-push: lint test
# === OK_EDIT: mytool standard ===

# === DO_NOT_EDIT: mytool coverage ===
cov:
  uv run pytest --cov
# === OK_EDIT: mytool coverage ===
"""


# === DO_NOT_EDIT: pkg-ext class_commentconfig ===
class CommentConfigExample(Example):
    prefix: str = ...  # type: ignore
    suffix: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_commentconfig ===

comment_config_hash = CommentConfigExample(
    example_name="hash_comments",
    prefix="#",
    suffix="",
)

comment_config_html = CommentConfigExample(
    example_name="html_comments",
    prefix="<!--",
    suffix=" -->",
)


# === DO_NOT_EDIT: pkg-ext class_get_comment_config ===
class GetCommentConfigExample(Example):
    path: Path | str = ...  # type: ignore
    override: CommentConfig | None = ...  # type: ignore
    expected_prefix: str = ...  # type: ignore
    expected_suffix: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_get_comment_config ===

get_comment_config_python = GetCommentConfigExample(
    example_name="python_file",
    path=Path("test.py"),
    override=None,
    expected_prefix="#",
    expected_suffix="",
)

get_comment_config_markdown = GetCommentConfigExample(
    example_name="markdown_file",
    path=Path("test.md"),
    override=None,
    expected_prefix="<!--",
    expected_suffix=" -->",
)

get_comment_config_override = GetCommentConfigExample(
    example_name="with_override",
    path=Path("test.py"),
    override=CommentConfig("%%"),
    expected_prefix="%%",
    expected_suffix="",
)


# === DO_NOT_EDIT: pkg-ext class_parse_sections ===
class ParseSectionsExample(Example):
    content: str = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore
    expected_section_count: int = ...  # type: ignore
    expected_first_id: str = ...  # type: ignore
    expected_first_content: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_parse_sections ===

parse_sections_justfile = ParseSectionsExample(
    example_name="justfile_sections",
    content=JUSTFILE_CONTENT,
    tool_name="mytool",
    config=HASH_CONFIG,
    expected_section_count=2,
    expected_first_id="standard",
    expected_first_content="pre-push: lint test",
)

parse_sections_html = ParseSectionsExample(
    example_name="html_sections",
    content="""\
<!-- === DO_NOT_EDIT: pkg heading === -->
# Title
<!-- === OK_EDIT: pkg heading === -->
""",
    tool_name="pkg",
    config=HTML_CONFIG,
    expected_section_count=1,
    expected_first_id="heading",
    expected_first_content="# Title",
)


# === DO_NOT_EDIT: pkg-ext class_replace_sections ===
class ReplaceSectionsExample(Example):
    dest_content: str = ...  # type: ignore
    src_sections: dict[str, str] = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore
    skip_sections: list[str] | None = ...  # type: ignore
# === OK_EDIT: pkg-ext class_replace_sections ===
    expected_contains: str = ...  # type: ignore
    expected_not_contains: str = ...  # type: ignore



replace_sections_existing = ReplaceSectionsExample(
    example_name="replace_existing",
    dest_content="""\
# === DO_NOT_EDIT: t std ===
old content
# === OK_EDIT: t std ===""",
    src_sections={"std": "new content"},
    tool_name="t",
    config=HASH_CONFIG,
    skip_sections=None,
    expected_contains="new content",
    expected_not_contains="old content",
)

replace_sections_skip = ReplaceSectionsExample(
    example_name="skip_section",
    dest_content="""\
# === DO_NOT_EDIT: t std ===
preserved
# === OK_EDIT: t std ===""",
    src_sections={"std": "would be replaced"},
    tool_name="t",
    config=HASH_CONFIG,
    skip_sections=["std"],
    expected_contains="preserved",
    expected_not_contains="would be replaced",
)
