# === DO_NOT_EDIT: pkg-ext header ===
"""Parameterized tests for sections group. Generated by pkg-ext."""

import pytest

from zero_3rdparty import sections_examples as examples_module
from zero_3rdparty.sections import get_comment_config, parse_sections, replace_sections, CommentConfig
# === OK_EDIT: pkg-ext header ===

# === DO_NOT_EDIT: pkg-ext commentconfig_test_parametrize ===
commentconfig_examples = [
    e for e in vars(examples_module).values() if isinstance(e, examples_module.CommentConfigExample)
]


@pytest.mark.parametrize("example", commentconfig_examples, ids=[e.example_name for e in commentconfig_examples])
def test_commentconfig(example: examples_module.CommentConfigExample):
    instance = CommentConfig(**example.model_dump(exclude={"example_name", "example_description_md"}))
    example.expected(example, instance)


# === OK_EDIT: pkg-ext commentconfig_test_parametrize ===

# === DO_NOT_EDIT: pkg-ext get_comment_config_test_parametrize ===
get_comment_config_examples = [
    e for e in vars(examples_module).values() if isinstance(e, examples_module.GetCommentConfigExample)
]


@pytest.mark.parametrize(
    "example", get_comment_config_examples, ids=[e.example_name for e in get_comment_config_examples]
)
def test_get_comment_config(example: examples_module.GetCommentConfigExample):
    result = get_comment_config(path=example.path, override=example.override)
    example.expected(example, result)


# === OK_EDIT: pkg-ext get_comment_config_test_parametrize ===

# === DO_NOT_EDIT: pkg-ext parse_sections_test_parametrize ===
parse_sections_examples = [
    e for e in vars(examples_module).values() if isinstance(e, examples_module.ParseSectionsExample)
]


@pytest.mark.parametrize("example", parse_sections_examples, ids=[e.example_name for e in parse_sections_examples])
def test_parse_sections(example: examples_module.ParseSectionsExample):
    result = parse_sections(content=example.content, tool_name=example.tool_name, config=example.config)
    example.expected(example, result)


# === OK_EDIT: pkg-ext parse_sections_test_parametrize ===

# === DO_NOT_EDIT: pkg-ext replace_sections_test_parametrize ===
replace_sections_examples = [
    e for e in vars(examples_module).values() if isinstance(e, examples_module.ReplaceSectionsExample)
]


@pytest.mark.parametrize("example", replace_sections_examples, ids=[e.example_name for e in replace_sections_examples])
def test_replace_sections(example: examples_module.ReplaceSectionsExample):
    result = replace_sections(
        dest_content=example.dest_content,
        src_sections=example.src_sections,
        tool_name=example.tool_name,
        config=example.config,
        skip_sections=example.skip_sections,
    )
    example.expected(example, result)


# === OK_EDIT: pkg-ext replace_sections_test_parametrize ===
