# === DO_NOT_EDIT: pkg-ext header ===
"""Example classes for sections group. Generated by pkg-ext."""

from collections.abc import Callable
from pathlib import Path
from typing import Generic, Self, TypeVar

from pydantic import BaseModel, Field

from zero_3rdparty._internal.sections import CommentConfig, Section

T = TypeVar("T")


class Example(BaseModel, Generic[T]):
    example_name: str
    example_description_md: str = ""
    expected: Callable[[Self, T], None] = Field(exclude=True)


# === OK_EDIT: pkg-ext header ===
# === DO_NOT_EDIT: pkg-ext class_commentconfig ===
class CommentConfigExample(Example[CommentConfig]):
    prefix: str = ...  # type: ignore
    suffix: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_commentconfig ===
# === DO_NOT_EDIT: pkg-ext class_get_comment_config ===
class GetCommentConfigExample(Example[CommentConfig]):
    path: Path | str = ...  # type: ignore
    override: CommentConfig | None = ...  # type: ignore


# === OK_EDIT: pkg-ext class_get_comment_config ===
# === DO_NOT_EDIT: pkg-ext class_parse_sections ===
class ParseSectionsExample(Example[list[Section]]):
    content: str = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore
    filename: str = ...  # type: ignore


# === OK_EDIT: pkg-ext class_parse_sections ===
# === DO_NOT_EDIT: pkg-ext class_replace_sections ===
class ReplaceSectionsExample(Example[str]):
    dest_content: str = ...  # type: ignore
    src_sections: dict[str, str] | list[Section] = ...  # type: ignore
    tool_name: str = ...  # type: ignore
    config: CommentConfig = ...  # type: ignore
    skip_sections: list[str] | None = ...  # type: ignore
    keep_deleted_sections: bool = ...  # type: ignore


# === OK_EDIT: pkg-ext class_replace_sections ===
